name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: windows-11
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for letting us know your issue. We will look into that shortly."
        pr-message: "Thank you for submitting a pull request. Our developers will look into it and will merge it if required."
